# Makefile - ST Microelectronics STM32F2xx series
#
# Copyright (c) 2016 RnDity Sp. z o.o.
# Copyright (c) 2017 Jérôme Guéry
#
# SPDX-License-Identifier: Apache-2.0
#

obj-y += soc.o

obj-$(CONFIG_GPIO) += soc_gpio.o
obj-$(CONFIG_PINMUX) += soc_pinmux.o
